name: spanda
channels:
  - conda-forge
  - fastchan
  - fastai
  - pytorch
  - spectrocat/label/dev

dependencies:
  - python=3.9.13
  - nbdev
  - notebook
  - fastai
  - tqdm
  - numpy
  - pandas
  - matplotlib
  - brukeropusreader
