# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/spanda',
                'doc_host': 'https://franckalbinet.github.io',
                'git_url': 'https://github.com/franckalbinet/spanda',
                'lib_path': 'spanda'},
  'syms': {'spanda.core': {'spanda.core.foo': ('core.html#foo', 'spanda/core.py')}}}